-- ============================================================================
-- EAUMALIK SARL — Seed manuel (mot de passe à fournir HORS de ce fichier).
--
-- 1. Créez l'utilisateur via Supabase Dashboard (Authentication > Users > Add user)
--    OU via service-role (cf. script Node ci-dessous — NE JAMAIS écrire de mdp ici).
--
-- 2. Promouvez en admin :
--      UPDATE public.users
--         SET role = 'admin'
--       WHERE email = 'eaumaliksarl@gmail.com';
--
-- 3. Exemple Node (script CI) :
--      const { data, error } = await supabaseAdmin.auth.admin.createUser({
--        email: 'eaumaliksarl@gmail.com',
--        password: process.env.SEED_ADMIN_PASSWORD,
--        email_confirm: true,
--        user_metadata: { full_name: 'Administrateur EAUMALIK', role: 'admin' },
--      });
--
-- ⚠️ Le mot de passe NE DOIT JAMAIS apparaître dans ce fichier ni dans le repo.
